from pages.BasePage import BasePage
from selenium.webdriver.common.by import By

class LoginPageLocators:
    LOGIN_FIELD = (By.ID, 'field_email')
    PASSWORD_FIELD = (By.ID, 'field_password')
    LOGIN_BUTTON = (By.XPATH, '//*[@data-test-id="enter-action"]')
    SEARCH_INPUT = (By.XPATH, '//input[@data-tsid="toolbar-search-input"]')
    SHOW_PASSWORD_BUTTON = (By.XPATH, '//button[contains(., "Показать пароль")]')
    QR_LOGIN_BUTTON = (By.XPATH, '//button[@label="Войти по QR-коду"]')
    TROUBLE_LOGIN_BUTTON = (By.XPATH, '//button[@aria-label="Не получается войти?"]')
    REGISTER_BUTTON = (By.XPATH, '//button[contains(., "Зарегистрироваться")]')
    LOGIN_QR_CODE_BUTTON = (By.XPATH, '//a[@data-l="t,qr_tab"]')
    LOGIN_WITH_VK_ID = (By.XPATH, '//a[@data-l="t,vkc"]')
    LOGIN_WITH_MAIL = (By.XPATH, '//a[@data-l="t,mailru"]')
    LOGIN_WITH_YANDEX = (By.XPATH, '//a[@data-l="t,yandex"]')
    LANGUAGE_SWITCH_LINK = (By.XPATH, '//a[@href="/dk?st.cmd=anonymMain&cmd=PopLayer&st.layer.cmd=PopLayerChooseNewLanguage"]')
    HOBBIES_LINK = (By.XPATH, '//a[@data-l="t,hobby"]')
    GROUPS_LINK = (By.XPATH, '//a[@data-l="t,groups"]')
    PUBLICATIONS_LINK = (By.XPATH, '//a[@data-l="t,.c"]')
    PEOPLE_LINK = (By.XPATH, '//a[@data-l="t,profiles"]')
    VIDEO_LINK = (By.XPATH, '//a[@data-l="t,video"]')
    GIFTS_LINK = (By.XPATH, '//a[@data-l="t,altGroupPresents"]')
    GAMES_LINK= (By.XPATH, '//a[@data-l="t,appsInfo"]')
    ADVERTISERS_LINK = (By.XPATH, '//a[@data-l="t,advertiser"]')
    HELP_LINK = (By.XPATH, '//a[@data-l="t,help"]')
    MORE_BUTTON = (By.XPATH, '//button[contains(@class, "more-popup_btn")]')
    NEWS_LINK = (By.ID, 'nohook_footer_news')
    VACANCIES_LINK = (By.XPATH, '//a[@data-l="t,jobs"]')
    ABOUT_COMPANY_LINK = (By.XPATH, '//a[@data-l="t,aboutCompany"]')
    FOR_BUSINESS_LINK = (By.XPATH, '//a[@data-l="t,business"]')
    FOR_DEVELOPERS_LINK = (By.XPATH, '//a[@data-l="t,apiWiki"]')
    AGREEMENTS_LINK = (By.XPATH, '//a[@data-l="t,agreementPage"]')
    LOGO_LINK = (By.ID, 'nohook_logo_link')
    VK_SERVICES_BUTTON = (By.XPATH, '//button[@aria-label="Сервисы VK"]')
    MAIL_LINK = (By.XPATH, '//a[@data-l="t,mail"]')
    VK_CLOUD_LINK = (By.XPATH, '//a[@data-l="t,cloud"]')
    VK_PORTAL_LINK = (By.XPATH, '//a[@data-l="t,portal"]')
    VK_CALENDAR_LINK = (By.XPATH, '//a[@data-l="t,calendar"]')
    VK_NOTES_LINK = (By.XPATH, '//a[@data-l="t,notes"]')
    VK_CALLS_LINK = (By.XPATH, '//a[@data-l="t,calls"]')
    VK_MAIL_LINK = (By.XPATH, '//a[@data-l="t,vk_mail"]')
    VK_TV_LINK = (By.XPATH, '//a[@data-l="t,tv"]')
    VK_WEATHER_LINK = (By.XPATH, '//a[@data-l="t,weather"]')
    VK_HOROSCOPE_LINK = (By.XPATH, '//a[@data-l="t,horoscope"]')
    VK_SPORT_LINK = (By.XPATH, '//a[@data-l="t,sport"]')
    VK_ANSWERS_LINK = (By.XPATH, '//a[@data-l="t,answers"]')
    VK_LADY= (By.XPATH, '//a[@data-l="t,lady"]')
    VK_ADS_LINK = (By.XPATH, '//a[@data-l="t,vkr"]')
    VKONTAKTE_LINK = (By.XPATH, '//a[@data-l="t,vk"]')
    VK_ECOSYSTEM_MORE_LINK = (By.XPATH, '//a[@data-l="t,more"]')



class LoginPageHelper(BasePage):
    pass